attempt: aa_latlon
dataset: geoguess-ai/panorama-div9

panorama_crop:
  fov: [60, 100]
  heading: [-180, 180]
  pitch: [-30, 30]
  roll: [-10, 10]

batch_size: 16

precision: bf16-mixed
precision_matmul: medium

steps: 100000
learning_rate: 2.0e-4
