attempt: bd_panocuda
dataset: geoguess-ai/panorama-div9-2048

panorama_crop: {}
randomize_heading: true
image_size: [512, 512]

batch_size: 16

precision: bf16-mixed
precision_matmul: medium

steps: 100000
learning_rate: 2.0e-4
accumulate_grad: 1

num_times: 4
