attempt: bd_panocuda
dataset: geoguess-ai/panorama-div9-1024-jpeg

panorama_crop: {}
randomize_heading: false
image_size: [224, 224]

batch_size: 64

precision: bf16-mixed
precision_matmul: medium

steps: 100000
learning_rate: 8.0e-4
accumulate_grad: 1

num_times: 4
