attempt: bd_panocuda
dataset: geoguess-ai/panorama-div9-1024-jpeg

panorama_crop:
  fov: [80, 100]
  heading: [-10, 10]
  pitch: [-40, 40]
  roll: [-5, 5]
randomize_heading: true
image_size: [224, 224]
four_side: true

batch_size: 32

precision: bf16-mixed
precision_matmul: medium

steps: 100000
learning_rate: 8.0e-4
accumulate_grad: 1

num_times: 4
