attempt: ca_baseline
dataset: geoguess-ai/panorama-div9-1024-jpeg

image_size: [224, 224]
randomize_heading: true
panorama_crop:
  fov: [80, 100]
  heading: [-10, 10]
  pitch: [-40, 40]
  roll: [-5, 5]
four_side: true

batch_size: 32

precision: bf16-mixed
precision_matmul: medium

warmup_steps: 1000
steps: 100000
learning_rate: 2.0e-4
accumulate_grad: 1

diffusion_steps: 100
init_noise_scale: 1.0

num_times: 4
